# 🛠️ 00. TensorFlow Fundamentals Exercises

https://github.com/mrdbourke/tensorflow-deep-learning#-00-tensorflow-fundamentals-exercises

In [2]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [12]:
# scalar, matrix, tensor (everything)
scalar = tf.constant(1)
matrix = tf.constant([[1, 2],
                      [3, 4]])
tensor = matrix

In [11]:
# shape, rank, size
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [15]:
# reate two tensors containing random values between 0 and 1 with shape [5, 300]
random_tensor1 = tf.random.uniform(minval=0, maxval=1, shape=[5, 300])
random_tensor2 = tf.random.uniform(minval=0, maxval=1, shape=[5, 300])

random_tensor1, random_tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.36970735, 0.50229824, 0.59194744, ..., 0.6623018 , 0.3646245 ,
         0.71988046],
        [0.37393177, 0.54611564, 0.45953965, ..., 0.4274794 , 0.27410698,
         0.84106195],
        [0.8666861 , 0.6081947 , 0.15223062, ..., 0.2572968 , 0.09097171,
         0.03160107],
        [0.5572884 , 0.855425  , 0.93545747, ..., 0.624105  , 0.7614237 ,
         0.13321888],
        [0.93095386, 0.59524477, 0.6876596 , ..., 0.5786369 , 0.86475265,
         0.4515339 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7101493 , 0.79121673, 0.24622059, ..., 0.6212096 , 0.06560099,
         0.31916702],
        [0.5077152 , 0.9829669 , 0.9336773 , ..., 0.9807373 , 0.49211752,
         0.05010712],
        [0.8375453 , 0.6372113 , 0.677181  , ..., 0.11482215, 0.82463837,
         0.73068297],
        [0.39624476, 0.3921615 , 0.9478911 , ..., 0.42856073, 0.32610166,
         0.77775526],
        [0.28507

In [20]:
# Multiply the two tensors you created in 3 using matrix multiplication.
random_tensor1 * 3, random_tensor2 * 3

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[1.109122  , 1.5068947 , 1.7758423 , ..., 1.9869053 , 1.0938735 ,
         2.1596413 ],
        [1.1217953 , 1.6383469 , 1.378619  , ..., 1.2824382 , 0.82232094,
         2.5231857 ],
        [2.6000583 , 1.8245841 , 0.45669186, ..., 0.7718904 , 0.27291512,
         0.09480321],
        [1.6718652 , 2.5662751 , 2.8063724 , ..., 1.8723149 , 2.2842712 ,
         0.39965665],
        [2.7928615 , 1.7857343 , 2.0629787 , ..., 1.7359107 , 2.5942578 ,
         1.3546017 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[2.1304479 , 2.37365   , 0.73866177, ..., 1.8636289 , 0.19680297,
         0.95750105],
        [1.5231457 , 2.9489007 , 2.801032  , ..., 2.942212  , 1.4763526 ,
         0.15032136],
        [2.5126357 , 1.911634  , 2.031543  , ..., 0.34446645, 2.473915  ,
         2.192049  ],
        [1.1887343 , 1.1764845 , 2.8436732 , ..., 1.2856822 , 0.978305  ,
         2.3332658 ],
        [0.85523

In [21]:
# Multiply the two tensors you created in 3 using dot product.
random_tensor1 @ 3, random_tensor2 @ 3

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [5,300] vs. [] [Op:MatMul] name: 

In [24]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tensor3 = tf.random.uniform(shape=[224, 224, 3])
tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8289794 , 0.04844785, 0.34551096],
        [0.19097042, 0.6718644 , 0.96260345],
        [0.00848866, 0.5154251 , 0.7791922 ],
        ...,
        [0.62118995, 0.1625936 , 0.4110794 ],
        [0.37511635, 0.75019884, 0.7830881 ],
        [0.48927546, 0.31759906, 0.18420184]],

       [[0.89675975, 0.46978998, 0.3960142 ],
        [0.97747993, 0.6877085 , 0.29279578],
        [0.31882012, 0.55671227, 0.7034751 ],
        ...,
        [0.298321  , 0.22641027, 0.344105  ],
        [0.08577669, 0.8320917 , 0.71773314],
        [0.71385634, 0.12759256, 0.72938824]],

       [[0.91338146, 0.9399686 , 0.3491012 ],
        [0.04033816, 0.86023486, 0.9575492 ],
        [0.92817676, 0.68937886, 0.9304594 ],
        ...,
        [0.7616123 , 0.856498  , 0.8934442 ],
        [0.31522572, 0.3633077 , 0.25904453],
        [0.8282597 , 0.47558653, 0.6975814 ]],

       ...,

       [[0.13504219, 0.3682679 , 0.51460576],
        [0.30

In [26]:
# Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_min(tensor3, 1), tf.reduce_max(tensor3, 1), 

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[3.74042988e-03, 2.27010250e-03, 1.22572184e-02],
        [6.02006912e-03, 1.82137489e-02, 4.43029404e-03],
        [6.23822212e-04, 2.17878819e-03, 7.24351406e-03],
        [2.22361088e-03, 1.50096416e-03, 6.38413429e-03],
        [5.04791737e-03, 1.33287907e-03, 8.58116150e-03],
        [1.04947090e-02, 4.96435165e-03, 1.58154964e-03],
        [7.34412670e-03, 4.03404236e-04, 1.90186501e-03],
        [2.88486481e-03, 4.87732887e-03, 1.83820724e-03],
        [5.17261028e-03, 6.81889057e-03, 3.88967991e-03],
        [1.54268742e-03, 3.09717655e-03, 2.24471092e-04],
        [1.96099281e-04, 3.45695019e-03, 3.42857838e-03],
        [1.34696960e-02, 1.91032887e-03, 8.11815262e-04],
        [4.79602814e-03, 7.67433643e-03, 2.05326080e-03],
        [2.83312798e-03, 4.03511524e-03, 6.47544861e-04],
        [2.11238861e-04, 7.11071491e-03, 5.57172298e-03],
        [7.80224800e-03, 2.73263454e-03, 3.36503983e-03],
        [8.85128975e-

In [28]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor4 = tf.random.uniform(shape=[1, 224, 224, 3])
tensor4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.5640435 , 0.13520277, 0.4970914 ],
         [0.5951761 , 0.92428327, 0.64567184],
         [0.04147696, 0.06784999, 0.00529325],
         ...,
         [0.24825323, 0.73761165, 0.42434418],
         [0.85460734, 0.96645   , 0.51816845],
         [0.42987466, 0.7347387 , 0.5241345 ]],

        [[0.1612823 , 0.41499996, 0.5467247 ],
         [0.41104186, 0.25450087, 0.37713242],
         [0.62666035, 0.39672303, 0.1868738 ],
         ...,
         [0.41954815, 0.06339133, 0.8874918 ],
         [0.45066357, 0.7779963 , 0.12799895],
         [0.07632744, 0.33332467, 0.33275282]],

        [[0.10600507, 0.01977134, 0.5310252 ],
         [0.17052746, 0.93977547, 0.9469985 ],
         [0.9442339 , 0.17078829, 0.07722664],
         ...,
         [0.72370076, 0.40768683, 0.56036437],
         [0.02443182, 0.13056147, 0.05154598],
         [0.05211031, 0.37596655, 0.49751616]],

        ...,

        [[0.12975013, 0.30958295, 

In [30]:
tensor4 = tf.squeeze(tensor4)
tensor4.shape

TensorShape([224, 224, 3])

In [34]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
import numpy as np
tensor5 = tf.constant(np.random.randint(0, 100, size=10), shape=[10])
tensor5, tf.argmax(tensor5)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([65, 57, 40, 99, 45, 76, 16, 34, 59, 33])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=3>)

In [41]:
tf.one_hot(tensor5, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## 00. TensorFlow Fundamentals Extra-curriculum